### ISSUE TITLE
Accurate initialScrollIndex scrolling problem

### ISSUE THREAD

**Issue by mbilenko-florio** [LegendApp/legend-list#13]
Let's imagine we have a list with two distinct types of elements, one of them is callled "separator", second one is called "item".  Currently we have estimatedItemLength function, and theoretically we can get each item's height by index.

![Simulator Screenshot - iPhone 15 - 2024-11-23 at 17 03 31](https://github.com/user-attachments/assets/236468b4-c2ce-411d-bec3-6d1223f33b00)

Let's also imagine, that we need to provide ``` initialScrollIndex={50}``` and scroll precisely to this element.  To have accurate scrolling possibility i need to enforce each item height in the renderItem, and provide exact values in the estimatedItemLength, otherwise correct scrolling is not possible. But with current LegendList api accurate scroll is still not possible. Let me explain why: 

Initial scroll offset is calculated using 
```
  const initialContentOffset =
            initialScrollOffset ??
            (initialScrollIndex ? initialScrollIndex * estimatedItemLength(initialScrollIndex) : undefined);
```
This is outright not imprecise calculation, because it assumes that all list elements have height of the estimatedItemLength(initialScrollIndex).

Also when calculating number of containers(allocateContainers), 

```
 const numContainers =
                initialContainers || Math.ceil((scrollLength + scrollBuffer * 2) / estimatedItemLength(0)) + 4;
``` 
We assume that all list elements of the same height, and use estimatedItemLength(0) for estimation. If first list item is separator, and has pretty short length, this leads to erroneous overallocation of containers and worse performance.

To solve those edge cases I propose to change props of the LegendList to following:
```
 estimatedAverateItemLength: number;
 estimatedItemLength?: (index: number) => number;
 ```
 For most users usage of estimatedAverateItemLength should be more then enough. If user has more insights about element length, then he can provide additional estimatedItemLength function which will give more insights about elements height.
 
 I experimented a little bit with a fork of a library, and can create PR, but want do discuss API changes first, because it's a bit of breaking change.

**Comment by jmeistrich** [comment]
Oh that's a very good point. I had added an `initialContainers` prop to specify the number of containers manually when estimation is way off, but that's probably not friendly enough, and probably not a good prop name anyway 😅

Also I realized that I should have named things "Size" instead of "Length" to match other libraries' props. So I think we should change that, add an average one like you're suggesting, and rename initialContainers:

- estimatedItemSize
- estimatedAverageItemSize
- initialNumContainers

Then I think we should also change the behavior to allow one or both of `estimatedItemSize` and `estimatedAverageItemSize`. So I'd add a `getItemLength` helper function in there which gets it from `estimatedItemSize` if available or otherwise get it from `estimatedAverageItemSize`, and replace the current usage of `estimatedItemLength` with that. 

And replace the two instances you mentioned where the current behavior is wrong with `estimatedAverageItemSize`.

If you'd like to create a PR to do some or all of that, it would be awesome :)

**Comment by mbilenko-florio** [comment]
@jmeistrich Thanks for confirming my thoughts. I will gladly create a PR.

**Comment by mbilenko-florio** [comment]
When trying to implement new api i've found out that estimatedItemSize and estimatedAverageItemSize are quite confusing.
Instead I went with
```
 estimatedItemSize: number;
 getEstimatedItemSize?: (index: number, item: T) => number;
 ```
 Names bit more self explainatory, and it's easier to understand where is value, and where function. 
 
 Link to PR: https://github.com/LegendApp/legend-list/pull/16

**Comment by jmeistrich** [comment]
I was just looking at that :). I think you're right that those are better names. I'll take a more in depth look at it tomorrow. Thank you!
