### ISSUE TITLE
Visible list item height readjustments

### ISSUE THREAD

**Issue by mbilenko-florio** [LegendApp/legend-list#30]
Platform: Android(new arch on)
Library version: 0.4.6

When testing on the android I found this interesting artifact, it's actually visible, that library is using estimated size to place items, then measures them, and puts into the proper positions.
This results in visible layout jump. It's not critical, but quite annoying. Is it just part of how this library measures children? Should we hide list until initial measurements round is finished? 
https://github.com/user-attachments/assets/0f001ee7-c7b4-43a8-a813-b5ac27763497

Reproducer example: 
https://github.com/mbilenko-florio/ListReadjustmentDemo

**Comment by mbilenko-florio** [comment]
I've thought about possible ways to solve it. One way is create containerMeasured flag, which will display item with opacity:0 while measuring, and display it only when it's final position is known. 

@jmeistrich Can you take a look at this draft? https://github.com/LegendApp/legend-list/commit/6e55c02ace5d42068974ffe4bbe31b63f010ed26

Downside of this approach is there will be more blanking during scroll. Should it be enabled separately with some prop?

**Comment by arasrezaei** [comment]
This issue is the one stop many using legend list. There are a lot of jumping when the items are extremely different sized. We can show a spinner or loading while calculating new items in the range.

**Comment by jmeistrich** [comment]
This should be fixed in 0.5.0. It now hides containers until they've been rendered for the first time. 

Thanks @mbilenko-florio for that draft! That turned out to be pretty much the best way to do it :). But for some reason images weren't loading correctly in the movies example so I instead adjusted the position to be offscreen. But it seems to work well now in every example I tested with.

Please let me know if this is working well for you all now?
