### ISSUE TITLE
Feature: Missing ItemSeparatorComponent, ListEmptyComponent, ListFooterComponent, showsVerticalScrollIndicator, inverted

### ISSUE THREAD

**Issue by imranbarbhuiya** [LegendApp/legend-list#6]
- [x] ItemSeparatorComponent
- [x] ListEmptyComponent
- [x] ListFooterComponent
- [x] ListeHeaderComponent 
- [x] showsVerticalScrollIndicator
- [x] ref scrollToIndex
- [x] ref scrollToItem
- [x] ~~inverted~~
ref: https://reactnative.dev/docs/flatlist

**Comment by jmeistrich** [comment]
ListeHeaderComponent and ListFooterComponent were added in 0.1.2 by https://github.com/LegendApp/legend-list/pull/3.

I think `inverted` will not be added, but we will support chat-like views in a better way. But please let me know if you have a different reason for wanting inverted.

Thanks for creating a tracking issue for other missing props! Please feel free to submit a PR to add the others, I'm focusing on some other things first.

**Comment by imranbarbhuiya** [comment]
ok thanks, I need inverted for chat only so if you are adding a better way of doing it then it's great

**Comment by huextrat** [comment]
`showsVerticalScrollIndicator` & `showsHorizontalScrollIndicator` should already work, given the implementation, and it seems to work

Have you seen any non-functional behavior with these two props?

PR for `ItemSeparatorComponent`: https://github.com/LegendApp/legend-list/pull/8

**Comment by jmeistrich** [comment]
I added a chat-like feature in 0.2.1. See https://github.com/LegendApp/legend-list/pull/2 for some discussion of that. Does that effectively solve the usage you were wanted `inverted` for?

**Comment by imranbarbhuiya** [comment]
@huextrat you are right, I had it disabled for ios only and was checking in Android

**Comment by jmeistrich** [comment]
I added `viewabilityConfig` and `onViewableItemsChanged` and some of you legends added these PRs: 

Ref functions: https://github.com/LegendApp/legend-list/pull/19
EmptyListComponent: https://github.com/LegendApp/legend-list/pull/25
ItemSeparatorComponent: https://github.com/LegendApp/legend-list/pull/8
ListHeaderComponent & ListFooterComponent: https://github.com/LegendApp/legend-list/pull/3

So I think we now have all of the import FlatList props except for:
- `inverted`: Solved by `alignItemsAtEnd` to create a chat-like interface where items start at the bottom
- `columns`: I think it should be solved by just putting multiple columns in rows, unless I'm missing something?

Does anybody see any incorrect behavior in these props, any still missing props, or have good reasons why we should have `inverted` and `columns`? Or is anything not working correctly?

If not then I think we're feature complete for version 1 :)

### Future features beyond v1
- Maintaining visible scroll position when items above the view resize or are added. I had attempted it early on and had a partially working solution, but punted that to finish the basics.
- Possibly more DX improvements
- More performance testing and optimizations

### Known bugs
- [ ] Removing items can leave them still visible because the container was not recycled

### Things to check
- [ ] Are all of the API types correct?
- [ ] Are there props from ScrollView that should be omitted?
- [ ] Are there still any props/features from FlatList/FlashList that should be added?
- [ ] Are there any other bugs that there's not already an Issue for?
